unstable_features=true
use_small_heuristics="Max"
single_line_if_else_max_width=30
max_width=100
array_width=100
chain_width=100
struct_lit_width=15
use_field_init_shorthand=true
force_multiline_blocks=true
